version: "3.7"

services:

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    container_name: caddy

    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - ./data:/data
      - ./caddy_config:/config

    networks:
      - internal
      - web


networks:
  web:
    driver: bridge
  internal:
    driver: bridge
    internal: true