version: "3.7"

services:
  db:
    image: mariadb:10
    container_name: mariadb

    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - internal


